### ISSUE TITLE
HostVector uses class methods to store property indexes

### ISSUE THREAD

**Issue by jaromiru** [Jjschwartz/NetworkAttackSimulator#17]
The HostVector class defined in `nasim/envs/host_vector.py` uses `@classmethod` methods to store property indexes. This hinders possible scalability of the framework, if a mix of toplogies, number of subnets and hosts were used in one session.
 https://github.com/Jjschwartz/NetworkAttackSimulator/blob/4f78571bdb4f12c6d110829cc73e402246413e82/nasim/envs/host_vector.py#L365-L380

**Comment by jaromiru** [comment]
Nore: it probably makes sense to store the indexes in a class, since all vectors has to be of the same size, regardless of the fact that different scenarios may be used in the same session. It seems that a better solution would be to allow for an explicit initialization of the subnet / host address bounds with a known maximal value.

**Comment by jaromiru** [comment]
The value is taken from `scenario.address_space_bounds`, so a way to specify that explicitly (e.g., in `ScenarioGenerator.generate()` should be enough.

**Comment by Jjschwartz** [comment]
Hey jaromiru, as you mentioned, the property indexes are stored as class properties since all host vectors need to be the same dimension. However, I can see what you mean about limiting the scalability and flexibility if you want to run different scenarios in the same session. 

I've had a deeper look into this and it isn't as trivial as I first thought. 

Assuming the number of hosts, OS, services, processes are kept constant between the different scenarios, the change you suggested should work.   

However, making it so the observation space is consistent across scenarios where the number of hosts, OS, processes and or services change is more complicated. There are two main reasons for this:

1. The size of a host vector also depends on the number of OS, services and processes in the scenario
2. The number of rows in the observation space is determined by the number of hosts in the network rather than the address space bounds

There are definitely ways to deal with both issues. 

For issue 1, we could have bounds for OS, services and processes similar to the address space bounds, this wouldn't be too hard to add support for. 

Issue 2 is a bit trickier because the best way to deal with the limitation will depend on the use case. The current method, where the number of rows (i.e. hosts) in the observation and state tensors is equal to the number of hosts in the network. is ideal for use cases where the number of hosts between scenarios is the same since it will not include extra unused rows in the observation space and so keep the dimensions of the observation space to a minimum.  The other option would be to set the number of rows in the observation space to be based on the address space bounds, this will inevitably lead to empty rows in the observation space but will allow generalization to different topologies, number of subnets and number of hosts.

I'm going to add support to specifying custom address bounds to the `ScenarioGenerator.generate()` function so that it will be possible to use different topologies and number of subnets, given the number of hosts, OS, services and processes remains constant. I'm going to push these changes in v0.9.0.

Unfortunately, as I no longer actively work on this project or in the area I don't have the time or motivation for implementing updates for the other cases. However, I welcome any pull requests for them.

Thanks for raising the suggestion.

**Comment by jaromiru** [comment]
Hi Jonathon,

thanks for the thoughts and the effort in maintaining this.

1): It would be better and more general if `generate()` accepted address bounds (both subnets/hosts) and os/services/processes bounds as well.
2): Number of rows is not a problem, there are NNs variations that can cope with that (eg. GNNs/Deepsets/MILs/etc.)
