### ISSUE TITLE
The initial observation should include the address

### ISSUE THREAD

**Issue by jaromiru** [Jjschwartz/NetworkAttackSimulator#18]
The initial observation should include the address. If we assume that the attacker can only attack hosts with a known address, the current situation does not allow any action.

https://github.com/Jjschwartz/NetworkAttackSimulator/blob/4f78571bdb4f12c6d110829cc73e402246413e82/nasim/envs/state.py#L117-L118

The code should include `address=True`.

**Comment by Jjschwartz** [comment]
Hey jaromiru, thanks for the pull request. I think you may a good point. I'm a bit busy at the moment but plan to have a deeper look into this when I have some spare time within the next fortnight.

**Comment by Jjschwartz** [comment]
Your right. Technically within Nasim, whether the address is known or not does not affect whether a given action will succeed or fail, since action success firstly depends on reachability and discovery. However, I can see that depending on your assumptions and how you are using the environment, observing the initial address is essential. Furthermore, I can't see any reason that it shouldn't be included in the initial observation.

I'll incorporate the proposed fix. Thanks again for the contribution.

**Comment by Jjschwartz** [comment]
Resolved by pull request fix #20
