### ISSUE TITLE
Begging for q_learning.py

### ISSUE THREAD

**Issue by Joe-zsc** [Jjschwartz/NetworkAttackSimulator#2]
I am begging for the q_learning.py that Contains the Tabular Q-learning agents, could you please share with me

**Comment by Jjschwartz** [comment]
Hey Joe-zsc,

Just to clarify, you are after an example implementation of Tabular Q-Learning for NASim? I.e. something similar to the DQN implementation that is in the repo, but of course using tabular representation for the value function? 

I actually don't have an existing implementation of Tabular Q-Learning for the current version of NASim, since a lot has changed with NASim since I wrote my thesis. However, I will try implement it over the next few days since, now that you mention it, it would be useful to include.

**Comment by Joe-zsc** [comment]
> Hey Joe-zsc,
> 
> Just to clarify, you are after an example implementation of Tabular Q-Learning for NASim? I.e. something similar to the DQN implementation that is in the repo, but of course using tabular representation for the value function?
> 
> I actually don't have an existing implementation of Tabular Q-Learning for the current version of NASim, since a lot has changed with NASim since I wrote my thesis. However, I will try implement it over the next few days since, now that you mention it, it would be useful to include.

yes, I am after an example implementation of Tabular Q-Learning(with e-greedy and UCB)  for NASim. 
actually, I am reading your paper "AutonomousPenetrationTestingusingReinforcementLearning". your paper is a guide for my research and I'd appreciate it if you could share your code in this paper with me.
![image](https://user-images.githubusercontent.com/51767345/99658360-5b4c7680-2a9a-11eb-9b12-ae3559dd671d.png)

**Comment by Jjschwartz** [comment]
Ok, I have added an implemention of tabular Q-Learning to the latest version (v0.7.2) of the repo. 

https://github.com/Jjschwartz/NetworkAttackSimulator/blob/master/nasim/agents/ql_agent.py 

I have only implemented the epsilon greedy version of Q-Learning as it is much easier to implement and in the original paper it got the same or better performance than the UCB version. Unfortunately, my original code is no longer compatible with the current version of the NASim library and would require a bit of work to convert and it would we very compareable to the implementation I added.

I also added a Tabular Q-Learning agent which uses Experience Replay. I didn't have this in the original paper but its training is a bit more stable, but at the cost of more memory and compute.

https://github.com/Jjschwartz/NetworkAttackSimulator/blob/master/nasim/agents/ql_replay_agent.py 

I hope this helps and let me know if you have any issues with the Q-Learning agents.

**Comment by Joe-zsc** [comment]
how could I know the detail of actions that the agent chooses in each episode?
<img width="496" alt="97255fee57cdf1d58977dd90d2fa77b" src="https://user-images.githubusercontent.com/51767345/99898362-dc468080-2cdb-11eb-80cf-c10da82f0494.png">
when I run the `python ql_agent.py tiny`, it just show me the "steps done", "return" and "goal", but i want to know the detail of actions that the agent chooses.

**Comment by Jjschwartz** [comment]
Hey Joe, yep I think I understand what you mean.

In the latest version 0.7.3 I have added some extra functionallity to the DQN, QL and QL with replay agents so that you can optionally view the policy of the agent following training. You can do this by including the `--render_eval` flag when running any of the agents in the terminal, for example:

`$ python ql_agent.py tiny --render_eval`

Following training you can then view the policy in action. Note that in order to avoid a giant wall of text being generated all at once I made it so that the user has to press a key after each action.

If you want to have information about the actions being used during training you will need to modify the agents (specifically the `run_train_episode`) function or alternatively write your own agents. You can see an example of how I have done this in the `run_eval_episode` function of each agent.
