### ISSUE TITLE
Renaming of get_minimal_steps_to_goal()

### ISSUE THREAD

**Issue by rzvnbr** [Jjschwartz/NetworkAttackSimulator#38]
Hi,
If my understanding is correct, the implementation of the function `get_minimal_steps_to_goal()` in `utils.py` means that the function returns the minimum number of hops needed to traverse the network to reach the target. I believe this is different from the number of steps in pentesting sense, meaning the number of actions needed to reach the target, given that several actions may be required on a single node (e.g., exploit and privilege escalation). 
The confusion is even higher for me considering that this function is called by `NASimEnv.get_minimum_actions()`, whose name mentions "actions" explicitly. Based on its name, I would have expected it to return something similar to the number of actions specified in the optimal path for benchmarks scenarios, such as `tiny.yml`. Moreover, I think that the word "steps" is used in the pentesting sense when computing the pentesting score, so using it with a different meaning in the code is confusing.
Consequently, I suggest that the related functions are renamed (e.g., `get_minimum_hops_to_goal()`) to better reflect their actual meaning.
If by any chance my understanding is wrong, I would appreciate if you could explain why.
Best wishes,
Razvan

**Comment by Jjschwartz** [comment]
Hey Razvan, sorry for the slow reply.

Your understanding is correct, and agree the renaming as you suggested would be clearer. I initially implemented this function to give a simple lower bound on the number of actions, which is does since at least `min hops <= min actions` along the optimal path, but can see that the naming could introduce confusion. 

I renamed the function to `get_minimum_hops` (similar in the Network class) in the latest version (`v0.12.0`). 

Thanks as always for the suggestions.
